[project]
name = "Freela_Backend"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "kauabarros-24", email = "martinsbarroskaua@gmail.com"},
]
dependencies = [
    "django>=5.1",
    "django-rest-framework>=0.1.0",
    "djangorestframework-simplejwt>=5.3.1",
    "django-allauth>=64.2.0",
    "django-cors-headers>=4.4.0",
    "django-rest-framework-oauth>=0.0.2",
    "django-oauth-toolkit>=2.4.0",
    "oauth2>=1.5.211",
]
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false

[tool.pdm.scripts]
runserver = "python3 manage.py runserver"
makemigrations = "python3 manage.py makemigrations"
migrate = "python3 manage.py migrate"
newMasterMan = "python3 manage.py createsuperuser"
shellp = "python3 manage.py shell"
newApp = "django-admin startapp"

